{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Structure analysis after mini using lammps CG method for mini \n",
    "# Transfer all the calculations \n",
    "# Import project for post processing \n",
    "import numpy as np\n",
    "%matplotlib inline\n",
    "import matplotlib.pylab as plt\n",
    "from pyiron import Project\n",
    "import lammps_logfile\n",
    "import os\n",
    "import codecs\n",
    "utf8reader = codecs.getreader('utf-8')\n",
    "\n",
    "pr = Project(\"/nfshome/deshmukh/pyiron/projects/NASICON/project/hena/hena_1/glass\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/pysqa/utils/remote.py:235: UserWarning: \n",
      "  warnings.warn(stderr.read().decode())\n",
      " 64%|██████▎   | 7/11 [00:01<00:00,  6.49it/s]Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 739, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 988, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 682, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140423792854848 and this is thread id 140419001247488.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7fb67cba4a80>\n",
      "Traceback (most recent call last):\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 739, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 988, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 682, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140423792854848 and this is thread id 140419001247488.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 247, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 688, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140423792854848 and this is thread id 140419001247488.\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 739, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 988, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 682, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140423792854848 and this is thread id 140419001247488.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7fb67caef990>\n",
      "Traceback (most recent call last):\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 739, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 988, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 682, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140423792854848 and this is thread id 140419001247488.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 247, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 688, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140423792854848 and this is thread id 140419001247488.\n",
      "Exception during reset or similar\n",
      "Traceback (most recent call last):\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 739, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 988, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 682, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140423792854848 and this is thread id 140419001247488.\n",
      "Exception closing connection <sqlite3.Connection object at 0x7fb67caefb70>\n",
      "Traceback (most recent call last):\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 739, in _finalize_fairy\n",
      "    fairy._reset(pool)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 988, in _reset\n",
      "    pool._dialect.do_rollback(self)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 682, in do_rollback\n",
      "    dbapi_connection.rollback()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140423792854848 and this is thread id 140419001247488.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/pool/base.py\", line 247, in _close_connection\n",
      "    self._dialect.do_close(connection)\n",
      "  File \"/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 688, in do_close\n",
      "    dbapi_connection.close()\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140423792854848 and this is thread id 140419001247488.\n",
      "100%|██████████| 11/11 [11:37<00:00, 63.42s/it] \n",
      "100%|██████████| 1/1 [06:12<00:00, 372.26s/it]\n",
      "/nfshome/deshmukh/miniconda3/envs/vaibhav/lib/python3.9/site-packages/pysqa/utils/remote.py:235: UserWarning: \n",
      "  warnings.warn(stderr.read().decode())\n",
      "100%|██████████| 11/11 [10:51<00:00, 59.25s/it]\n",
      "100%|██████████| 1/1 [05:51<00:00, 351.41s/it]\n"
     ]
    }
   ],
   "source": [
    "# Calculate quech rate and time \n",
    "rate = range(1, 2, 1)\n",
    "#rate_1 = range(1, 11, 1)\n",
    "\n",
    "t = []     # time steps in fs \n",
    "for i in rate:\n",
    "    time = ((4000-300)/i)*1000\n",
    "    t.append(round(time))\n",
    "\n",
    "# For different colling rate \n",
    "\n",
    "strct_no = [5, 26, 28, 30, 25] #[43, 47, 4, 13, 42, 10, 5, 26, 28, 30, 25] \n",
    "\n",
    "for k in strct_no:\n",
    "    for i, j in zip(t, rate):\n",
    "        job = pr['hena_1_%s_rate_%s_k_ps'%(k,j)]\n",
    "        #job.output.energy_pot[-1]\n",
    "        job.transfer_from_remote()\n",
    "        job.compress()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9.13 ('vaibhav')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "c5882173ff5685180b15cb907f22c6bef76d5cc8695d1b8791e985617bfa7d2d"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
